### PR TITLE
983 requistion chart data

### PR DESCRIPTION
**Pull request by andreievg**
Some data to use for deving changes to new requisition chart end point,

put this data file in root (extracted): 
[chart_data.sqlite.zip](https://github.com/openmsupply/remote-server/files/8393729/chart_data.sqlite.zip)

then:

```gql
query MyQuery {
  requisitionLineChart(requestRequisitionLineId: "requisition_line", storeId: "store") {
    ... on ItemChartNode {
      calculationDate
      consumptionHistory {
        nodes {
          averageMonthlyConsumption
          consumption
          date
          isCurrent
          isHistoric
        }
      }
      stockEvolution {
        nodes {
          date
          isHistoric
          isProjected
          maximumStockOnHand
          stockOnHand
          minimumStockOnHand
        }
      }
      suggestedQuantityCalculation {
        averageMonthlyConsumption
        maximumStockOnHand
        minimumStockOnHand
        stockOnHand
        suggestedQuantity
      }
    }
    ... on RequisitionLineChartError {
      __typename
      error {
        description
      }
    }
  }
}

```

result 

```json
{
  "data": {
    "requisitionLineChart": {
      "calculationDate": "2021-01-02",
      "consumptionHistory": {
        "nodes": [
          {
            "averageMonthlyConsumption": 80,
            "consumption": 80,
            "date": "2020-02-29",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 73,
            "consumption": 60,
            "date": "2020-03-31",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 72,
            "consumption": 75,
            "date": "2020-04-30",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 77,
            "consumption": 100,
            "date": "2020-05-31",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 86,
            "consumption": 85,
            "date": "2020-06-30",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 87,
            "consumption": 80,
            "date": "2020-07-31",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 77,
            "consumption": 70,
            "date": "2020-08-31",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 92,
            "consumption": 130,
            "date": "2020-09-30",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 102,
            "consumption": 110,
            "date": "2020-10-31",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 108,
            "consumption": 85,
            "date": "2020-11-30",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 112,
            "consumption": 147,
            "date": "2020-12-31",
            "isCurrent": false,
            "isHistoric": true
          },
          {
            "averageMonthlyConsumption": 100,
            "consumption": 100,
            "date": "2021-01-31",
            "isCurrent": false,
            "isHistoric": false
          }
        ]
      },
      "stockEvolution": {
        "nodes": [
          {
            "date": "2020-12-04",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 115,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-05",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 110,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-06",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 110,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-07",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 110,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-08",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 102,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-09",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 92,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-10",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 90,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-11",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 87,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-12",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 84,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-13",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 84,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-14",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 79,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-15",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 74,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-16",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 74,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-17",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 71,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-18",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 64,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-19",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 60,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-20",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 60,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-21",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 60,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-22",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 59,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-23",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 53,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-24",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 46,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-25",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 44,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-26",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 44,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-27",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 44,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-28",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 39,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-29",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 29,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-30",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 24,
            "minimumStockOnHand": 30
          },
          {
            "date": "2020-12-31",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 24,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-01",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 22,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-02",
            "isHistoric": true,
            "isProjected": false,
            "maximumStockOnHand": 200,
            "stockOnHand": 20,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-03",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 16,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-04",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 13,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-05",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 10,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-06",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 6,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-07",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 3,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-08",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 0,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-09",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 0,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-10",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 0,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-11",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 0,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-12",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 176,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-13",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 173,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-14",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 169,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-15",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 166,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-16",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 163,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-17",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 159,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-18",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 156,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-19",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 153,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-20",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 149,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-21",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 146,
            "minimumStockOnHand": 30
          },
          {
            "date": "2021-01-22",
            "isHistoric": false,
            "isProjected": true,
            "maximumStockOnHand": 200,
            "stockOnHand": 143,
            "minimumStockOnHand": 30
          }
        ]
      },
      "suggestedQuantityCalculation": {
        "averageMonthlyConsumption": 100,
        "maximumStockOnHand": 200,
        "minimumStockOnHand": 30,
        "stockOnHand": 20,
        "suggestedQuantity": 180
      }
    }
  }
}
```

### CODE REVIEW

**Comment by mark-prins** [comment]
Just wondering, why is the calculationDate `2021-01-02`? When did you do this?!

**Comment by andreievg** [comment]
> Just wondering, why is the calculationDate `2021-01-02`? When did you do this?!

Hehe thats why charts took so long, I had to invent time machine first

Btw calculation date = date AMC and SOH was calculated, it would typically be when requisition line was added (in this case I just started with 2021 01 02, for no real reason)

**Comment by mark-prins** [comment]
> Btw calculation date = date AMC and SOH was calculated, it would typically be when requisition line was added (in this case I just started with 2021 01 02, for no real reason)

aah, right! that makes sense.. thanks

**Comment by andreievg** [comment]
Closing, I think it served it's purpose

**Pull request closed without merging**
