### PR TITLE
#244 docs social and cta button link updates

### LINKED ISSUE #244: Docs social and CTA button links need updating
- The docs page CTA button links to `getting-started/introduction` which was deleted
- The social buttons link to adidoks repo and twitter which is nice and thoughtful but I think unintended

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #244 

Hm, unsure if this is the right branch 🤷 

- social icons change from : https://github.com/aaranxu/adidoks/issues/7 - added a link to `msupply.foundation` cause seemed lonely. Was going to add my twitters but opted out. Maybe we add our fb page or twitters later. Maybe craigs twitter, I bet he's got some juuuuicy twits
- Unsure if the cta should go here, but seems OK
- git diff had all the code gen from the build so ignored?

### CODE REVIEW

**Comment by joshxg** [comment]
Hm.

GH Page build failing. I reverted my gitignore update as a guess, but getting

`remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.`

Wonder if something has changed recently which is breaking this, or have I done something wrong in the PR? Wrong branch?

**Review by mark-prins — COMMENTED** [review]
thanks - was going to do the same changes :)

**Comment by joshxg** [comment]
Oh.. with https://github.com/openmsupply/remote-server/pull/241 i'm not sure if I did something wrong or need to commit to a new branch? Sorry! Help! 😢

**Review by mark-prins — APPROVED** [review]
🎉  Changes look good to me!

**Comment by wlthomson** [comment]
> 
> 
> Hm.
> 
> GH Page build failing. I reverted my gitignore update as a guess, but getting
> 
> `remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.`
> 
> Wonder if something has changed recently which is breaking this, or have I done something wrong in the PR? Wrong branch?

This should be fixed now, the `gh-pages` branch had write protection on it to prevent people directly pushing to it (turns out it meant the action couldn't either!).

**Review by wlthomson — APPROVED** [review]

**Pull request merged**
