### PR TITLE
#288 Add testing github action

### LINKED ISSUE #288: Add test github action

### PR DESCRIPTION
**Pull request by clemens-msupply**
Closes #288.

I configured this action to run on a pull request to main. Should we do the same for the docs?

### CODE REVIEW

**Comment by andreievg** [comment]
> I configured this action to run on a pull request to main. Should we do the same for the docs?

Hmm, have to think where rust docs will live. We have our dev docs now, then we need rust docs and schema docs https://github.com/openmsupply/remote-server/issues/230

As for this PR, it looks good, I would call it sqlite tests though. And maybe mention this action in dev docs sometime

**Review by andreievg — APPROVED** [review]

**Comment by clemens-msupply** [comment]
I renamed the test and fixed the build feature which has changed in the meantime...

**Comment by clemens-msupply** [comment]
Tests are currently failing will fix it before merging...

**Comment by andreievg** [comment]
@clemens-msupply this is quite low on priority list tbh, so if you think it's going to take a lot of time, we can leave PR open for M2

**Comment by clemens-msupply** [comment]
Was an actual bug/regression and easy to find...

**Pull request merged**
