### PR TITLE
#274 correct git hub action yml syntax

### LINKED ISSUE #274: Docs site action failing to run
https://github.com/openmsupply/remote-server/actions/runs/1176367999/workflow

I guess it's yaml syntax error

Update: Yeah, I checked in a yaml checkerer https://onlineyamltools.com/ and it's invalid - so just a super minor one

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #274 

No idea what I'm doing 🙃

### CODE REVIEW

**Comment by joshxg** [comment]
Can I test this somehow? 🤷

**Comment by joshxg** [comment]
OK Well I got an email saying it was still broken.. so I tried fixing it.. and now i've stopped getting emails so either

1) It's fixed
2) It's way more broken

I'm not sure how to trigger the workflow to run manually 😢

**Comment by wlthomson** [comment]
@joshxg 😆 

rebase

**Comment by wlthomson** [comment]
> 
> 
> Can I test this somehow? 🤷

Tested!

See https://dev.msupply.foundation (shouldn't update until this is merged!):

image

For future reference, I use https://github.com/nektos/act. You'll need to setup a personal access token for the authentication, which I found a bit finicky. Might be easier to just temporarily update the action config to run on push to the branch you're working on (that's how I used to do it).

**Review by wlthomson — APPROVED** [review]

**Comment by joshxg** [comment]
@wlthomson hehe thanks ❤️

**Pull request merged**
